name: Generate FAQ list

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  faq-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install python modules
        run: pip install requests
      - name: Confirm python
        run: python -V
      - name: Generate FAQ list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python ./getfaqlist.py > faq.md
      - name: Commit if changes
        run: |
          git status -s
          if ! git diff --exit-code --quiet
          then
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            git add .
            git commit -m "FAQ list updated by actions"
            git push
          fi


    
